version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: youssef
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-youssefhadoud1234@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - rabbitmq
  apigtw:
    image: youssefhadoud/apigtw:latest
    container_name: apigtw
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
    networks:
      - rabbitmq

  customer:
    image: youssefhadoud/costumer:latest
    container_name: customer
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
    networks:
      - postgres
      - rabbitmq


  eurekaserver:
    image: youssefhadoud/eurekaservices:latest
    container_name: eurekaserver
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - apigtw
    networks:
      - rabbitmq

  fraud:
    image: youssefhadoud/fraud:latest
    container_name: fraud
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - zipkin
      - eurekaserver
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - rabbitmq
      - postgres

  notification:
    image: youssefhadoud/notification:latest
    container_name: notification
    ports:
      - "8090:8090"
    depends_on:
      - postgres
      - eurekaserver
      - zipkin
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - postgres
      - rabbitmq


networks:
  postgres:
    driver: bridge
  rabbitmq:
    driver: bridge




volumes:
  postgres:
  pgadmin:
