spring:
  application:
    name: notification
  datasource:
    username: youssef
    password: password
    url: jdbc:postgresql://postgres:5432/notification
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: rabbitmq:5672
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411


rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-key:
    internal-notification: internal.notification.routing-key


