server:
  port: 8080
spring:
  application:
    name: customer
  rabbitmq:
    addresses: rabbitmq:5672
  datasource:
    username: youssef
    password: password
    url: jdbc:postgresql://postgres:5432/customer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/


management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-key:
    internal-notification: internal.notification.routing-key



