server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
spring:
  application:
    name: eurekaservices

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411




